base_de_datos = [
  {
    "pregunta": 'Un paciente sufre traumatismo pterional: ¿qué estructura vascular se lacera con mayor frecuencia?',
    "opciones": ['Arteria meníngea media', 'Seno sagital superior', 'Arteria carótida externa', 'Vena facial'],
    "correcta": 0,
    "feedback_acierto": 'Correcto. Atención urgente a hematoma epidural.',
    "feedback_error": 'Incorrecto. Revise la anatomía del pterion y meníngeas.',
    "es_codigo_azul": False,
  },
  {
    "pregunta": '¿Qué nervio pasa por el foramen espinoso?',
    "opciones": ['Nervio mandibular (V3)', 'Arteria meníngea media', 'Nervio facial', 'Nervio vago'],
    "correcta": 1,
    "feedback_acierto": 'Bien: la arteria meníngea media transcurre por el foramen espinoso.',
    "feedback_error": 'No. El foramen spinosum transmite la arteria meníngea media.',
    "es_codigo_azul": False,
  },
  {
    "pregunta": '¿Qué foramen transmite la rama infraorbitaria del trigémino?',
    "opciones": ['Foramen infraorbitario', 'Foramen redondo', 'Foramen oval', 'Foramen magnum'],
    "correcta": 0,
    "feedback_acierto": 'Correcto: infraorbitario para V2.',
    "feedback_error": 'Incorrecto. La rama V2 sale por el foramen infraorbitario.',
    "es_codigo_azul": False,
  },
  {
    "pregunta": 'Un adenoma suprasellar comprime fibras superiores del quiasma: ¿qué defecto visual aparecerá?',
    "opciones": ['Hemianopsia bitemporal superior', 'Hemianopsia bitemporal inferior', 'Pérdida monocular', 'Escotoma central'],
    "correcta": 0,
    "feedback_acierto": 'Correcto: compresión superior produce pérdida de fibras inferonasales → superior visual.',
    "feedback_error": 'No es esa. Revise la disposición de fibras en el quiasma óptico.',
    "es_codigo_azul": False,
  },
  {
    "pregunta": 'CÓDIGO AZUL: paciente pierde pulso y conciencia tras fallo respiratorio. ¿Cuál es la prioridad inmediata?',
    "opciones": ['Iniciar RCP y soporte vital avanzado', 'Esperar signos vitales', 'Administrar antibióticos', 'Colocar sedación profunda'],
    "correcta": 0,
    "feedback_acierto": 'Correcto: RCP y ACLS son prioridad en Código Azul.',
    "feedback_error": 'Incorrecto y peligroso: en Código Azul se actúa ya.',
    "es_codigo_azul": True,
  },
  {
    "pregunta": '¿Qué estructura forma el límite anterior del triángulo carotídeo?',
    "opciones": ['Esternocleidomastoideo', 'Omohioideo', 'Vientre anterior del digástrico', 'Músculo trapecio'],
    "correcta": 0,
    "feedback_acierto": 'Bien. El SCM delimita el triángulo carotídeo lateralmente.',
    "feedback_error": 'No. Repase los límites del triángulo carotídeo.',
    "es_codigo_azul": False,
  },
  {
    "pregunta": 'La fascia carotídea envuelve principalmente:',
    "opciones": ['Vaina carotídea (carótida común, vena yugular interna, nervio vago)', 'Tronco simpático cervical', 'Tiroide', 'Faringe'],
    "correcta": 0,
    "feedback_acierto": 'Correcto: la vaina carotídea contiene esas estructuras.',
    "feedback_error": 'Incorrecto: no olvide el paquete vasculonervioso en la vaina.',
    "es_codigo_azul": False,
  },
  {
    "pregunta": '¿Qué nervio motor inerva el milohioideo?',
    "opciones": ['Rama del V3', 'Nervio hipogloso (XII)', 'Nervio facial (VII)', 'Cuerda del tímpano'],
    "correcta": 0,
    "feedback_acierto": 'Correcto: inervación por una rama de V3.',
    "feedback_error": 'No. El milohioideo es motor V3, revise bases de cabeza y cuello.',
    "es_codigo_azul": False,
  },
  {
    "pregunta": 'CÓDIGO AZUL: durante paro, ¿qué frecuencia cardíaca objetivo debe priorizarse para compresiones de alta calidad?',
    "opciones": ['Mantener compresiones a ritmo adecuado (100-120/min)', 'Sin compresiones', '90/min', '300/min'],
    "correcta": 0,
    "feedback_acierto": 'Correcto: 100-120 compresiones por minuto es objetivo ACLS.',
    "feedback_error": 'Incorrecto. Frecuencias extremas son contraproducentes.',
    "es_codigo_azul": True,
  },
  {
    "pregunta": 'En fosa pterigopalatina, una lesión puede dañar principalmente:',
    "opciones": ['Arteria maxilar y ramas de V2', 'Arteria temporal superficial', 'Seno cavernoso', 'Carótida interna'],
    "correcta": 0,
    "feedback_acierto": 'Correcto: maxilar y V2 son lo que atraviesa esa fosa.',
    "feedback_error": 'No. Revise relaciones anatómicas de la fosa pterigopalatina.',
    "es_codigo_azul": False,
  },
  {
    "pregunta": 'El foramen palatino menor transmite principalmente:',
    "opciones": ['Nervios palatinos menores (sensibilidad posterior)', 'Nervio infraorbitario', 'Nervio lingual', 'Arteria alveolar'],
    "correcta": 0,
    "feedback_acierto": 'Bien. Palatinos menores para mucosa posterior.',
    "feedback_error": 'Incorrecto: revise forámenes palatinos.',
    "es_codigo_azul": False,
  },
  {
    "pregunta": '¿Qué lesión del sistema simpático cervical produce miosis, ptosis y anhidrosis?',
    "opciones": ['Síndrome de Horner', 'Parálisis del III par', 'Parálisis facial periférica', 'Lesión del VII par'],
    "correcta": 0,
    "feedback_acierto": 'Correcto: Horner es simpático cervical.',
    "feedback_error": 'No. Esa tríada es típica de Horner.',
    "es_codigo_azul": False,
  },
  {
    "pregunta": 'CÓDIGO AZUL: ¿qué cambiarías en el monitor cuando detectas asistolia persistente tras maniobras?',
    "opciones": ['Confirmar ritmo, continuar RCP y preparar fármacos según ACLS', 'Apagar monitor', 'Administrar analgesia y esperar', 'Desconectar al paciente'],
    "correcta": 0,
    "feedback_acierto": 'Correcto: confirmar ritmo y seguir protocolo ACLS.',
    "feedback_error": 'Respuesta inaceptable en situación crítica.',
    "es_codigo_azul": True,
  },
  {
    "pregunta": "¿Qué arteria forma el 'sifón' dentro del seno cavernoso?",
    "opciones": ['Arteria carótida interna', 'Arteria basilar', 'Arteria cerebral media', 'Arteria vertebral'],
    "correcta": 0,
    "feedback_acierto": 'Correcto.',
    "feedback_error": 'No. Revise anatomía del seno cavernoso.',
    "es_codigo_azul": False,
  },
  {
    "pregunta": 'En una fractura de la base del cráneo que afecta la lámina cribosa del etmoides, además de la rinorrea de líquido cefalorraquídeo, ¿qué estructura vascular corre riesgo inminente de lesión al atravesar el conducto etmoidal anterior?',
    "opciones": ['A. Arteria etmoidal posterior', 'B. Arteria etmoidal anterior', 'C. Arteria esfenopalatina', 'D. Arteria oftálmica'],
    "correcta": 1,
    "feedback_acierto": 'Correcto. La arteria etmoidal anterior acompaña al nervio nasal interno. No es física cuántica.',
    "feedback_error": '¡Incompetente! La esfenopalatina está en la fosa pterigomaxilar. Si no sabe dónde está la lámina cribosa, dedíquese a la jardinería.',
    "es_codigo_azul": False,
  },
  {
    "pregunta": 'Durante una disección del hueso temporal, identifica la eminencia arcuata en la cara anterosuperior de la roca. ¿Qué estructura del labioerinto óseo se encuentra inmediatamente profunda a esta elevación?',
    "opciones": ['A. Cóclea', 'B. Conducto semicircular posterior', 'C. Conducto semicircular superior', 'D. Vestíbulo'],
    "correcta": 2,
    "feedback_acierto": 'Aceptable. El conducto superior moldea el hueso formando esa eminencia.',
    "feedback_error": '¡Error garrafal! ¿La cóclea? ¿Está adivinando? El conducto semicircular superior es el que forma el relieve. Vuelva a primer año.',
    "es_codigo_azul": False,
  },
  {
    "pregunta": 'Paciente con neuralgia del trigémino. Se planea abordar el ganglio de Gasser. ¿En qué depresión de la cara anterosuperior de la roca del temporal debe buscar este ganglio?',
    "opciones": ['A. Foseta de Gasser', 'B. Fosa subarcuata', 'C. Tegmen tympani', 'D. Hiato de Falopio'],
    "correcta": 0,
    "feedback_acierto": 'Bien. La foseta de Gasser aloja al ganglio del mismo nombre en el cavum de Meckel.',
    "feedback_error": '¡Patético! El tegmen tympani es el techo del tímpano. Si opera ahí dejará sordo al paciente antes de curarle el dolor. ¡Estudie!',
    "es_codigo_azul": False,
  },
  {
    "pregunta": 'En un abordaje quirúrgico de la fosa pterigomaxilar, usted necesita localizar el nervio vidiano. ¿Qué orificio corresponde a la salida de este nervio hacia la fosa?',
    "opciones": ['A. Agujero redondo mayor', 'B. Conducto pterigopalatino', 'C. Conducto vidiano', 'D. Agujero esfenopalatino'],
    "correcta": 2,
    "feedback_acierto": 'Era una pregunta regalada. El conducto vidiano está en la base de la apófisis pterigoides.',
    "feedback_error": '¡Vergonzoso! ¿El agujero redondo mayor? Por ahí pasa el maxilar superior. ¡Es un peligro público con un bisturí en la mano!',
    "es_codigo_azul": False,
  },
  {
    "pregunta": 'Identifique la estructura ligamentosa que convierte la escotadura coracoidea del omóplato en un orificio osteofibroso por donde pasa el nervio supraescapular.',
    "opciones": ['A. Ligamento acromiocoracoideo', 'B. Ligamento coracoideo', 'C. Ligamento conoide', 'D. Ligamento trapezoide'],
    "correcta": 1,
    "feedback_acierto": 'Correcto. El nervio pasa por el orificio, la arteria suele pasar por encima.',
    "feedback_error": '¡Falso! El acromiocoracoideo forma la bóveda del hombro, no cierra esa escotadura. ¿Acaso distingue una escotadura de una articulación?',
    "es_codigo_azul": False,
  },
  {
    "pregunta": 'Paciente presenta hematoma epidural tras golpe en la región temporal. La arteria meníngea media ha sido lacerada. ¿Por qué orificio de la base del cráneo ingresa esta arteria?',
    "opciones": ['A. Agujero oval', 'B. Agujero redondo mayor', 'C. Agujero redondo menor (espinoso)', 'D. Agujero rasgado anterior'],
    "correcta": 2,
    "feedback_acierto": 'Correcto. Ingresa por el espinoso. Actúe rápido antes de que el paciente se hernie.',
    "feedback_error": '¡Asesino! El oval es para el mandibular. Mientras usted duda, el paciente muere. ¡Es el redondo menor!',
    "es_codigo_azul": True,
  },
  {
    "pregunta": 'En la cara exocraneana del occipital, ¿qué músculo se inserta en la superficie rugosa comprendida entre las líneas curvas occipitales superior e inferior, en su parte externa?',
    "opciones": ['A. Trapecio', 'B. Complexo mayor', 'C. Recto posterior menor', 'D. Oblicuo menor (superior) de la cabeza'],
    "correcta": 3,
    "feedback_acierto": 'Sorprendente. El oblicuo menor se inserta ahí. No esperaba que supiera miología profunda.',
    "feedback_error": '¡No! El trapecio va a la línea superior. Confunde lo superficial con lo profundo. Váyase a estudiar veterinaria.',
    "es_codigo_azul": False,
  },
  {
    "pregunta": 'Usted está operando una fístula del conducto de Stenon. ¿Sobre qué músculo descansa este conducto antes de perforar el buccinador?',
    "opciones": ['A. Temporal', 'B. Masetero', 'C. Pterigoideo interno', 'D. Risorio'],
    "correcta": 1,
    "feedback_acierto": 'Correcto. Cruza la cara externa del masetero. Cuidado con el nervio facial.',
    "feedback_error": '¡Inepto! ¿Sobre el temporal? El conducto está en la mejilla, no en la sien. Repase las relaciones de la parótida.',
    "es_codigo_azul": False,
  },
  {
    "pregunta": 'Paciente con desviación de la lengua hacia la derecha al protruirla. ¿Qué nervio está lesionado y qué orificio del cráneo atraviesa para salir?',
    "opciones": ['A. Nervio glosofaríngeo; Agujero rasgado posterior', 'B. Nervio hipogloso; Agujero condíleo anterior', 'C. Nervio lingual; Agujero oval', 'D. Nervio facial; Agujero estilomastoideo'],
    "correcta": 1,
    "feedback_acierto": 'Bien. El hipogloso motor de la lengua sale por el condíleo anterior (precondíleo).',
    "feedback_error": '¡Lamentable! El lingual es sensitivo. El motor es el hipogloso. ¿Cómo pretende diagnosticar si no sabe anatomía básica?',
    "es_codigo_azul": False,
  },
  {
    "pregunta": 'En una traqueostomía de urgencia, usted debe evitar lesionar las venas yugulares anteriores. ¿En qué espacio aponeurótico se encuentran estos vasos?',
    "opciones": ['A. Espacio prevertebral', 'B. Espacio supraesternal (de Gruber)', 'C. Vaina carotídea', 'D. Espacio retrovisceral'],
    "correcta": 1,
    "feedback_acierto": 'Correcto. El espacio supraesternal contiene las yugulares anteriores y ganglios.',
    "feedback_error": '¡Si corta ahí matará al paciente! El espacio supraesternal es la respuesta. Repase las aponeurosis cervicales inmediatamente.',
    "es_codigo_azul": True,
  },
  {
    "pregunta": 'Al disecar el triángulo de Pirogoff en el cuello, ¿qué estructura anatómica forma el suelo o fondo de este triángulo?',
    "opciones": ['A. Músculo milohioideo', 'B. Músculo hiogloso', 'C. Músculo constrictor medio de la faringe', 'D. Músculo estilohioideo'],
    "correcta": 1,
    "feedback_acierto": 'Exacto. El hiogloso forma el fondo, y la arteria lingual pasa profunda a él.',
    "feedback_error": '¡Error de principiante! El milohioideo es un límite, no el fondo. El fondo es el hiogloso. ¿Estudió con dibujos animados?',
    "es_codigo_azul": False,
  },
  {
    "pregunta": 'Se observa una fractura del hueso maxilar superior que separa la apófisis palatina del resto del hueso. ¿Qué conducto formado por la unión de ambos maxilares en la línea media anterior podría verse comprometido?',
    "opciones": ['A. Conducto palatino posterior', 'B. Conducto palatino anterior (incisivo)', 'C. Conducto suborbitario', 'D. Conducto dentario anterior'],
    "correcta": 1,
    "feedback_acierto": 'Correcto. El conducto palatino anterior está detrás de la espina nasal anterior.',
    "feedback_error": '¡Absurdo! El palatino posterior está atrás, cerca de la pterigoides. Ubíquese espacialmente o dedíquese a la filosofía.',
    "es_codigo_azul": False,
  },
  {
    "pregunta": '¿Qué músculo se inserta en la foseta escafoidea de la apófisis pterigoides y utiliza el gancho del ala interna como polea de reflexión?',
    "opciones": ['A. Peristafilino interno (Petrosalpingostafilino)', 'B. Peristafilino externo (Esfenosalpingostafilino)', 'C. Pterigoideo interno', 'D. Pterigoideo externo'],
    "correcta": 1,
    "feedback_acierto": 'Bien. El peristafilino externo se refleja en el gancho. Al menos sabe algo de paladar.',
    "feedback_error": '¡Incorrecto! El interno es recto. El externo es el que usa la polea. ¡Vaya a estudiar los músculos del velo del paladar!',
    "es_codigo_azul": False,
  },
  {
    "pregunta": 'En la articulación temporomaxilar, ¿qué ligamento se inserta en la espina del esfenoides y en la espina de Spix (língula) de la mandíbula?',
    "opciones": ['A. Ligamento estilomaxilar', 'B. Ligamento pterigomaxilar', 'C. Ligamento esfenomaxilar', 'D. Ligamento lateral externo'],
    "correcta": 2,
    "feedback_acierto": 'Correcto. El ligamento esfenomaxilar es un ligamento auxiliar importante.',
    "feedback_error": '¡Qué ignorancia! El estilomaxilar va de la estiloides. Es el esfenomaxilar. ¿Sabe leer los nombres de las estructuras?',
    "es_codigo_azul": False,
  },
  {
    "pregunta": 'Paciente con lesión del nervio facial dentro del acueducto de Falopio, distal al ganglio geniculado pero proximal a la salida de la cuerda del tímpano. ¿Qué función estará conservada?',
    "opciones": ['A. Gusto de los 2/3 anteriores de la lengua', 'B. Secreción de la glándula lagrimal', 'C. Movilidad de los músculos de la mímica', 'D. Secreción de la glándula submaxilar'],
    "correcta": 1,
    "feedback_acierto": 'Lógica pura. El nervio petroso superficial mayor (lagrimal) sale a nivel del ganglio geniculado, antes de la lesión.',
    "feedback_error": '¡Piense! Los petrosos salen en el ganglio. Si la lesión es distal, la lágrima está bien. ¡Repase la vía del facial!',
    "es_codigo_azul": False,
  },
  {
    "pregunta": '¿Qué estructura anatómica pasa por el espacio comprendido entre el músculo escaleno anterior y el escaleno medio?',
    "opciones": ['A. Vena subclavia', 'B. Arteria subclavia y plexo braquial', 'C. Nervio frénico', 'D. Arteria carótida primitiva'],
    "correcta": 1,
    "feedback_acierto": 'Correcto. El desfiladero de los escalenos. Sitio clásico de compresión.',
    "feedback_error": '¡Quiere matar al paciente! La vena va delante del escaleno anterior. La arteria va DETRÁS. ¡Peligro público!',
    "es_codigo_azul": True,
  },
  {
    "pregunta": 'La arteria meníngea media atraviesa el agujero redondo menor. ¿Qué nervio la acompaña en su trayecto o pasa muy próximo a ella antes de entrar al cráneo?',
    "opciones": ['A. Nervio maxilar inferior (V3)', 'B. Nervio recurrente meníngeo (de Luschka)', 'C. Nervio petroso menor', 'D. Cuerda del tímpano'],
    "correcta": 0,
    "feedback_acierto": 'Técnicamente el V3 pasa por el oval, pero están adyacentes en el ala mayor. Aceptable.',
    "feedback_error": '¡No tiene idea! El V3 y la meníngea media son vecinos en el esfenoides. Estudie los orificios del ala mayor.',
    "es_codigo_azul": False,
  },
  {
    "pregunta": 'Identifique el músculo que se inserta en la foseta digital de la cara interna del trocánter mayor.',
    "opciones": ['A. Obturador externo', 'B. Obturador interno', 'C. Piramidal', 'D. Glúteo medio'],
    "correcta": 0,
    "feedback_acierto": 'Correcto. El obturador externo termina en la foseta digital.',
    "feedback_error": '¡Error! El obturador interno va por encima de la foseta. Es el externo. ¡Mire un fémur alguna vez en su vida!',
    "es_codigo_azul": False,
  },
  {
    "pregunta": 'El conducto de Wharton de la glándula submaxilar cruza un nervio importante en el piso de la boca. ¿Cuál es ese nervio?',
    "opciones": ['A. Nervio hipogloso', 'B. Nervio lingual', 'C. Nervio glosofaríngeo', 'D. Nervio milohioideo'],
    "correcta": 1,
    "feedback_acierto": 'Sí. El conducto cruza al nervio lingual. Relación clásica.',
    "feedback_error": '¡No! El hipogloso está más profundo. Es el lingual el que hace el bucle. ¿Piensa seccionar el nervio al operar el conducto?',
    "es_codigo_azul": False,
  },
  {
    "pregunta": '¿Qué estructura ósea separa el conducto auditivo interno del orificio del acueducto del vestíbulo en la cara posterosuperior del peñasco?',
    "opciones": ['A. Eminencia arcuata', 'B. Fosa subarcuata', 'C. Tegmen tympani', 'D. Foseta de Gasser'],
    "correcta": 1,
    "feedback_acierto": 'Bien. La fosa subarcuata es el vestigio del canal petromastoideo.',
    "feedback_error": '¡Geografía ósea básica! La eminencia arcuata está en la cara ANTERIOR. Es la fosa subarcuata. ¡Repase el temporal!',
    "es_codigo_azul": False,
  },
  {
    "pregunta": 'En una fractura de la diáfisis humeral a nivel del canal de torsión, ¿qué estructuras vasculonerviosas corren mayor riesgo de lesión?',
    "opciones": ['A. Nervio mediano y arteria humeral', 'B. Nervio radial y arteria humeral profunda', 'C. Nervio cubital y arteria colateral interna superior', 'D. Nervio musculocutáneo y arteria circunfleja'],
    "correcta": 1,
    "feedback_acierto": 'Correcto. El canal de torsión aloja al radial y la humeral profunda.',
    "feedback_error": '¡Desastroso! El mediano va por dentro. Si lesiona el radial, tendrá mano péndula. ¡Estudie las relaciones del húmero!',
    "es_codigo_azul": True,
  },
  {
    "pregunta": '¿Qué ligamento de la articulación de la cadera limita la extensión del muslo y ayuda a mantener la estación bípeda sin gasto muscular excesivo?',
    "opciones": ['A. Ligamento iliofemoral (de Bertin)', 'B. Ligamento isquiofemoral', 'C. Ligamento pubofemoral', 'D. Ligamento redondo'],
    "correcta": 0,
    "feedback_acierto": 'Correcto. El ligamento de Bertin es el más fuerte y frena la extensión.',
    "feedback_error": '¡Falso! El isquiofemoral limita la rotación interna. Es el de Bertin. ¿Cómo se mantiene usted de pie sin saber esto?',
    "es_codigo_azul": False,
  },
  {
    "pregunta": 'Al examinar la faringe, identifica el músculo constrictor superior. ¿En qué estructura ósea se inserta su extremo superior y posterior?',
    "opciones": ['A. Espina de la esfenoides', 'B. Tubérculo faríngeo del occipital', 'C. Apófisis estiloides', 'D. Gancho del ala interna de la pterigoides'],
    "correcta": 1,
    "feedback_acierto": 'Correcto. Se cuelga del tubérculo faríngeo en la base del cráneo.',
    "feedback_error": '¡Incorrecto! El gancho es inserción anterior (pterigomaxilar). Atrás va al tubérculo faríngeo. ¡Estudie la base del cráneo!',
    "es_codigo_azul": False,
  },
  {
    "pregunta": '¿Qué arteria pasa por el agujero estilomastoideo para irrigar la caja del tímpano y los conductos semicirculares?',
    "opciones": ['A. Arteria timpánica anterior', 'B. Arteria estilomastoidea', 'C. Arteria meníngea media', 'D. Arteria faríngea ascendente'],
    "correcta": 1,
    "feedback_acierto": 'Obvio. Entra por donde sale el facial.',
    "feedback_error": '¡Por Dios! Se llama igual que el agujero. Arteria estilomastoidea. ¿Necesita que se lo dibuje?',
    "es_codigo_azul": False,
  },
  {
    "pregunta": 'La vena yugular interna se origina en el agujero rasgado posterior. ¿Qué senos venosos confluyen para formarla?',
    "opciones": ['A. Seno longitudinal superior y recto', 'B. Seno lateral (sigmoideo) y seno petroso inferior', 'C. Seno cavernoso y seno petroso superior', 'D. Seno transverso y seno occipital'],
    "correcta": 1,
    "feedback_acierto": 'Correcto. El seno lateral se continúa y recibe al petroso inferior en el golfo.',
    "feedback_error": '¡No! El seno lateral es el principal, pero el petroso inferior se le une allí. Repase la circulación venosa intracraneal.',
    "es_codigo_azul": False,
  },
  {
    "pregunta": '¿Qué músculo se inserta en el labio superior del borde posterior de la espina del omóplato?',
    "opciones": ['A. Deltoides', 'B. Trapecio', 'C. Supraespinoso', 'D. Infraespinoso'],
    "correcta": 1,
    "feedback_acierto": 'Bien. El trapecio se inserta en el labio superior, el deltoides en el inferior.',
    "feedback_error": '¡Error! El deltoides está en el labio INFERIOR. El supraespinoso está en la fosa. ¡Qué falta de precisión!',
    "es_codigo_azul": False,
  },
  {
    "pregunta": 'Paciente con fractura del tercio medio de la clavícula. ¿Qué músculo tracciona el fragmento interno hacia arriba?',
    "opciones": ['A. Pectoral mayor', 'B. Esternocleidomastoideo', 'C. Subclavio', 'D. Deltoides'],
    "correcta": 1,
    "feedback_acierto": 'Correcto. El ECM tira hacia arriba, el peso del brazo tira del fragmento externo hacia abajo.',
    "feedback_error": '¡Falso! El pectoral tira hacia dentro. Es el esternocleidomastoideo el que eleva. ¡Biomecánica básica de fracturas!',
    "es_codigo_azul": False,
  },
  {
    "pregunta": '¿Qué estructura pasa por el agujero sacrociático menor (escotadura ciática menor)?',
    "opciones": ['A. Músculo piramidal', 'B. Músculo obturador interno', 'C. Nervio ciático mayor', 'D. Vasos glúteos superiores'],
    "correcta": 1,
    "feedback_acierto": 'Correcto. El obturador interno sale de la pelvis por ahí.',
    "feedback_error": '¡No! El piramidal y el ciático van por la MAYOR. Por la menor va el obturador interno. ¡Qué confusión tiene en la pelvis!',
    "es_codigo_azul": False,
  },
  {
    "pregunta": 'Identifique el elemento que forma el límite interno del anillo crural.',
    "opciones": ['A. Vena femoral', 'B. Ligamento de Gimbernat', 'C. Cintilla iliopectínea', 'D. Ligamento de Cooper'],
    "correcta": 1,
    "feedback_acierto": 'Correcto. El ligamento lacunar o de Gimbernat es el borde cortante interno.',
    "feedback_error": '¡Peligroso! Si opera una hernia y no sabe esto, lesionará la vena femoral. El límite interno es el ligamento de Gimbernat.',
    "es_codigo_azul": True,
  },
  {
    "pregunta": '¿Qué músculo de la pierna tiene su tendón perforado por los ramos cutáneos del nervio musculocutáneo antes de insertarse en el peroné?',
    "opciones": ['A. Peroneo lateral largo', 'B. Peroneo lateral corto', 'C. Peroneo anterior', 'D. Sóleo'],
    "correcta": 1,
    "feedback_acierto": 'Detalle fino. El peroneo lateral corto. Bien.',
    "feedback_error": 'No. Es el peroneo lateral corto. Lea la letra pequeña de los libros, no solo los dibujos.',
    "es_codigo_azul": False,
  },
  {
    "pregunta": 'En la cara posterior del peñasco, ¿qué estructura se encuentra en la foseta ungueal, cerca del acueducto del vestíbulo?',
    "opciones": ['A. Saco endolinfático', 'B. Orificio del conducto auditivo interno', 'C. Hiato de Falopio', 'D. Ganglio de Gasser'],
    "correcta": 0,
    "feedback_acierto": 'Correcto. El acueducto del vestíbulo aloja al saco endolinfático.',
    "feedback_error": '¡Incorrecto! El CAI está más adelante. La foseta ungueal aloja el saco endolinfático. Anatomía del oído interno, doctor.',
    "es_codigo_azul": False,
  },
  {
    "pregunta": '¿Qué nervio inerva al músculo tensor del tímpano (músculo del martillo)?',
    "opciones": ['A. Nervio facial', 'B. Nervio mandibular (V3)', 'C. Nervio glosofaríngeo', 'D. Nervio vestibulococlear'],
    "correcta": 1,
    "feedback_acierto": 'Bien. Es rama del trigémino, no del facial.',
    "feedback_error": '¡Error clásico! El del estribo es del facial. El del martillo es del TRIGÉMINO (V3). ¡No confunda los huesecillos!',
    "es_codigo_azul": False,
  },
  {
    "pregunta": '¿Dónde se inserta el tendón del músculo poplíteo?',
    "opciones": ['A. Tuberosidad interna de la tibia', 'B. Foseta del poplíteo en el cóndilo externo del fémur', 'C. Cabeza del peroné', 'D. Línea áspera del fémur'],
    "correcta": 1,
    "feedback_acierto": 'Correcto. Es intraarticular en su origen femoral.',
    "feedback_error": '¡Falso! Se inserta en el cóndilo externo del fémur. Es un rotador de la rodilla. ¡Estudie la rodilla!',
    "es_codigo_azul": False,
  },
  {
    "pregunta": 'En la región de la nuca, ¿qué músculos delimitan el triángulo de los oblicuos (triángulo suboccipital) por donde pasa la arteria vertebral?',
    "opciones": ['A. Recto posterior mayor, oblicuo mayor y oblicuo menor', 'B. Recto posterior menor, recto posterior mayor y oblicuo mayor', 'C. Trapecio, esplenio y complexo', 'D. Recto lateral, recto anterior y largo del cuello'],
    "correcta": 0,
    "feedback_acierto": 'Bien. Recto mayor y los dos oblicuos. Contiene la arteria vertebral.',
    "feedback_error": '¡No! El recto menor no llega al triángulo. Son el recto mayor y los dos oblicuos. ¡Repase los planos profundos de la nuca!',
    "es_codigo_azul": False,
  },
  {
    "pregunta": '¿Qué estructura anatómica pasa a través del agujero ciático menor?',
    "opciones": ['A. Músculo piramidal', 'B. Nervio ciático', 'C. Músculo obturador interno y paquete pudendo interno', 'D. Arteria glútea superior'],
    "correcta": 2,
    "feedback_acierto": 'Correcto. El obturador interno sale por la menor, reingresa a la pelvis.',
    "feedback_error": '¡Error! El piramidal va por la mayor. El obturador interno y los pudendos van por la menor. ¡Anatomía pélvica básica!',
    "es_codigo_azul": False,
  },
  {
    "pregunta": 'En la mandíbula, la espina de Spix protege la entrada de:',
    "opciones": ['A. Nervio mentoniano', 'B. Nervio dentario inferior', 'C. Nervio lingual', 'D. Nervio milohioideo'],
    "correcta": 1,
    "feedback_acierto": 'Correcto. Punto clave para la anestesia troncular.',
    "feedback_error": '¡Increíble! Si no sabe dónde entra el dentario inferior, no debería acercarse a una boca. ¡Espina de Spix!',
    "es_codigo_azul": False,
  },
  {
    "pregunta": '¿Qué músculo de la eminencia tenar está inervado por el nervio cubital (ramo profundo)?',
    "opciones": ['A. Oponente del pulgar', 'B. Abductor corto del pulgar', 'C. Haz profundo del flexor corto del pulgar', 'D. Abductor largo del pulgar'],
    "correcta": 2,
    "feedback_acierto": 'Muy bien. El haz profundo del flexor corto y el aductor son cubitales.',
    "feedback_error": '¡Falso! La mayoría son del mediano, pero el haz profundo del flexor corto es CUBITAL. ¡Detalles que salvan manos!',
    "es_codigo_azul": False,
  },
  {
    "pregunta": '¿Qué estructura forma el límite posterior del conducto inguinal en su tercio interno (detrás del orificio superficial)?',
    "opciones": ['A. Tendón conjunto y ligamento de Colles', 'B. Fascia transversalis solamente', 'C. Aponeurosis del oblicuo mayor', 'D. Ligamento de Hesselbach'],
    "correcta": 0,
    "feedback_acierto": 'Correcto. El tendón conjunto refuerza la pared posterior medialmente.',
    "feedback_error": '¡Peligro de hernia! La pared posterior medial es fuerte gracias al tendón conjunto. ¡Repase el trayecto inguinal!',
    "es_codigo_azul": False,
  },
  {
    "pregunta": '¿En qué hueso se encuentra el canal de torsión del nervio radial?',
    "opciones": ['A. Húmero, cara posterior', 'B. Cúbito, cara externa', 'C. Radio, cuello', 'D. Omóplato, borde axilar'],
    "correcta": 0,
    "feedback_acierto": 'Básico. Cara posterior del húmero.',
    "feedback_error": '¡En el húmero! ¿Dónde cree que se rompe el húmero para lesionar el radial? ¡Despierte!',
    "es_codigo_azul": False,
  },
  {
    "pregunta": 'Identifique el músculo que se inserta en la apófisis estiloides del quinto metatarsiano.',
    "opciones": ['A. Peroneo lateral largo', 'B. Peroneo lateral corto', 'C. Tibial posterior', 'D. Peroneo anterior'],
    "correcta": 1,
    "feedback_acierto": 'Correcto. El corto va al quinto, el largo cruza la planta.',
    "feedback_error": '¡No! El largo cruza toda la planta hasta el primer metatarsiano. Es el CORTO el que va al quinto. ¡Mire un pie!',
    "es_codigo_azul": False,
  },
  {
    "pregunta": '¿Qué estructura anatómica atraviesa el espacio humerotricipital (cuadrilátero de Velpeau)?',
    "opciones": ['A. Nervio radial y arteria humeral profunda', 'B. Nervio circunflejo (axilar) y arteria circunfleja posterior', 'C. Arteria escapular inferior', 'D. Nervio cubital'],
    "correcta": 1,
    "feedback_acierto": 'Correcto. Circunflejo y arteria circunfleja posterior.',
    "feedback_error": '¡Error! El radial va por el triángulo humerotricipital. Por el cuadrilátero va el circunflejo. ¡Geometría de la axila, doctor!',
    "es_codigo_azul": False,
  },
  {
    "pregunta": '¿Qué ligamento vertebral se extiende desde el axis hasta el sacro por la cara posterior de los cuerpos vertebrales, dentro del conducto raquídeo?',
    "opciones": ['A. Ligamento vertebral común anterior', 'B. Ligamento vertebral común posterior', 'C. Ligamento amarillo', 'D. Ligamento supraespinoso'],
    "correcta": 1,
    "feedback_acierto": 'Correcto. Ligamento vertebral común posterior.',
    "feedback_error": '¡No! El amarillo une láminas. El común posterior va por detrás de los cuerpos. ¿Sabe dónde está el conducto raquídeo?',
    "es_codigo_azul": False,
  },
  {
    "pregunta": 'En la articulación de la rodilla, ¿dónde se inserta el ligamento cruzado anterior en la tibia?',
    "opciones": ['A. Superficie retroespinal', 'B. Superficie preespinal', 'C. Tuberosidad anterior', 'D. Espina de la tibia'],
    "correcta": 1,
    "feedback_acierto": 'Bien. Superficie preespinal (delante de la espina).',
    "feedback_error": '¡Al revés! El posterior va a la retroespinal. El anterior a la PREespinal. ¡Va a dejar inestable esa rodilla!',
    "es_codigo_azul": False,
  },
  {
    "pregunta": '¿Qué músculo forma el límite externo del triángulo de Scarpa?',
    "opciones": ['A. Aductor mediano', 'B. Sartorio', 'C. Recto interno', 'D. Pectíneo'],
    "correcta": 1,
    "feedback_acierto": 'Correcto. El sartorio es el límite externo.',
    "feedback_error": '¡Incorrecto! El aductor es el interno. El sartorio es el externo. ¿Confunde izquierda con derecha también?',
    "es_codigo_azul": False,
  },
  {
    "pregunta": 'La arteria uterina cruza por delante de una estructura vital cerca del cuello del útero. ¿Cuál es?',
    "opciones": ['A. Arteria ovárica', 'B. Uréter', 'C. Trompa de Falopio', 'D. Ligamento redondo'],
    "correcta": 1,
    "feedback_acierto": "Crucial. 'El agua pasa bajo el puente' (el uréter bajo la arteria).",
    "feedback_error": '¡Catástrofe! Si liga el uréter pensando que es un vaso, perderá el riñón. ¡La uterina cruza el uréter!',
    "es_codigo_azul": True,
  },
  {
    "pregunta": '¿Qué hueso del carpo se articula con el primer metacarpiano formando la articulación trapeciometacarpiana (silla de montar)?',
    "opciones": ['A. Escafoides', 'B. Trapecio', 'C. Trapezoide', 'D. Hueso grande'],
    "correcta": 1,
    "feedback_acierto": 'Correcto. Trapecio y primer metacarpiano.',
    "feedback_error": '¡No! Es el trapecio. Si no sabe esto, no entienda la oposición del pulgar. ¡Vaya a estudiar la mano!',
    "es_codigo_azul": False,
  },
  {
    "pregunta": '¿Qué seno paranasal drena en el meato superior?',
    "opciones": ['A. Seno frontal', 'B. Celdillas etmoidales posteriores', 'C. Seno maxilar', 'D. Conducto lacrimonasal'],
    "correcta": 1,
    "feedback_acierto": 'Correcto. Las etmoidales posteriores y el esfenoidal (receso esfenoetmoidal).',
    "feedback_error": '¡Mal! El frontal y el maxilar van al medio. Al superior van las etmoidales posteriores. ¡Repase la nariz!',
    "es_codigo_azul": False,
  },
  {
    "pregunta": '¿Qué músculo se inserta en la apófisis genio inferior de la mandíbula?',
    "opciones": ['A. Geniogloso', 'B. Geniohioideo', 'C. Milohioideo', 'D. Digástrico'],
    "correcta": 1,
    "feedback_acierto": 'Bien. Geniogloso arriba, geniohioideo abajo.',
    "feedback_error": '¡No! El geniogloso va a las superiores (lengua). El geniohioideo a las inferiores (hioides). ¡Qué confusión!',
    "es_codigo_azul": False,
  },
  {
    "pregunta": '¿Qué nervio inerva al músculo serrato mayor (anterior)?',
    "opciones": ['A. Nervio del dorsal ancho', 'B. Nervio respiratorio de Charles Bell (torácico largo)', 'C. Nervio circunflejo', 'D. Nervio subescapular'],
    "correcta": 1,
    "feedback_acierto": 'Correcto. Nervio de Charles Bell. Causa de escápula alada si se lesiona.',
    "feedback_error": '¡Error! Es el respiratorio de Bell. Si lo corta en una mastectomía, dejará al paciente con escápula alada.',
    "es_codigo_azul": False,
  },
  {
    "pregunta": '¿Qué ligamento refuerza la articulación temporomaxilar y se extiende desde la apófisis estiloides hasta el borde posterior de la rama ascendente?',
    "opciones": ['A. Ligamento esfenomaxilar', 'B. Ligamento estilomaxilar', 'C. Ligamento pterigomaxilar', 'D. Ligamento lateral externo'],
    "correcta": 1,
    "feedback_acierto": 'Correcto. El estilomaxilar es una cintilla de la fascia cervical profunda.',
    "feedback_error": '¡Su nombre lo dice! De estiloides a maxilar: ESTILOMAXILAR. ¿Tan difícil es?',
    "es_codigo_azul": False,
  },
]
